---
- name: "Create app folder"
  become: true
  file:
    path: /home/ubuntu/app

- name: "Unzip backend files for udapeople"
  become: true
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/app

- name: "Start server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: /home/ubuntu/app
